# Generated by Django 4.2.17 on 2024-12-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datagovernancerule_created_by_dataset_is_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datagovernancerule',
            options={'permissions': [('validate_rule', 'Can validate data governance rules')], 'verbose_name': 'Data Governance Rule', 'verbose_name_plural': 'Data Governance Rules'},
        ),
    ]
