# Generated by Django 4.2.17 on 2024-12-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dataset_uploaded_by'),
    ]

    operations = [
    ]
