# Generated by Django 4.2.17 on 2024-12-26 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20241226_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datagovernancerule',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='datagovernancerule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the rule is currently active'),
        ),
        migrations.AlterField(
            model_name='datagovernancerule',
            name='column_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datagovernancerule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datagovernancerule',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.dataset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datagovernancerule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datagovernancerule',
            name='rule_type',
            field=models.CharField(choices=[('format', 'Format'), ('range', 'Range'), ('required', 'Required'), ('unique', 'Unique'), ('categorical', 'Categorical'), ('date_format', 'Date Format'), ('cross_column', 'Cross Column')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='datagovernancerule',
            index=models.Index(fields=['dataset', 'rule_type'], name='core_datago_dataset_2f2b05_idx'),
        ),
        migrations.AddIndex(
            model_name='datagovernancerule',
            index=models.Index(fields=['column_name'], name='core_datago_column__036174_idx'),
        ),
    ]
